project:
  type: website

website:
  title: "Projetos"
  navbar:
    left:
      - href: index.qmd
        text: "Início"
      - href: https://github.com/cacbarros
        text: "GitHub"
  page-footer:
    center: "© 2025 C. A. C. Barros · [GitHub](https://github.com/cacbarros)"

format:
  html:
    theme: sandstone
    css: styles.css
